apiVersion: v1
kind: Service
metadata:
  name: mlops-project-service
spec:
  type: LoadBalancer
  selector:
    app: mlops-project
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
